### ISSUE TITLE
Node 4 compatibility

### ISSUE THREAD

**Issue by kevgo** [okunishinishi/node-tmplconv#3]
Node 4 is the current LTS version of Node. This library uses ES6 constructs, for example in https://github.com/okunishinishi/node-tmplconv/blob/master/lib/converting/convert.js#L17-L20.

Can you please transpile down to ES5 using BabelJS, to make this more compatible with older versions of Node?

**Comment by okunishinishi** [comment]
@kevgo 

I released v3.1.2 and it should work now. Can you try it?

**Comment by kevgo** [comment]
Thanks for the quick turn-around @okunishinishi! I have submitted #4 to let Travis-CI verify that tmplconv works on Node 4, 5, and 6. This way you don't have to juggle different Node versions on your machine!  😃

**Comment by kevgo** [comment]
I can't test this until you release the latest changes that fix Travis as 3.1.4. Thanks!
